---
title: "Physics 600 : Newtonian Perturbations"
author: "Nikhil Padmanabhan"
date: last-modified
date-format: iso
format:
  html:
    code-fold: true
    code-tools: true
    embed-resources: true
    html-math-method: mathjax
execute: 
  cache: true
---

These are the outlines and additional notes for the lectures on Newtonian perturbation theory.

## Outlines

### 2023-10-09 : Lecture 2

- Discuss the fluid equations for an expanding Universe in the Newtonian limit.

$$
\frac{\partial \rho}{\partial t} + 3 H \rho + \frac{1}{a} \nabla \cdot (\rho \vec{v}) = 0
$$
$$
\left( \frac{\partial}{\partial t} + \frac{\vec{v}}{a} \cdot \nabla \right) \vec{u} = - \frac{1}{a \rho} \nabla P - \frac{1}{a} \nabla \Phi
$$
$$
\nabla^2 \Phi = 4 \pi G a^2 \rho
$$



- Discussed the background unperturbed solution and show that this results in the 2nd Friedmann equation. The implication of this result is that we just need to track the perturbations of the non-relativistic components in eg. the Poisson equation (not the full energy components).  
- Two kinds of fluctuations
    - isentropic/adiabatic fluctuations where $\nabla S = 0$. 
        - fractional perturbations in species are equal.
        $$
        \frac{1}{3} \frac{\delta \rho_{CDM}}{\rho_{CDM}} = \frac{1}{3} \frac{\delta \rho_{b}}{\rho_{b}} = 
           \frac{1}{4} \frac{\delta \rho_{\gamma}}{\rho_{\gamma}} = \frac{1}{3} \frac{\delta \rho_{\nu}}{\rho_{\nu}} 
        $$
    - isocurvature fluctuations.
- Consider the linearized versions of these. 
    - Show that, in the absence of pressure and potential perturbations, $v$ decays with the scale factor.
    - density fluctuations are sourced by the divergence of the velocity perturbations. 
    - vorticity modes decay as $a^{-1}$ (take the curl of the Euler equation).


- Considering the Fourier transform of these
    - Fourier modes evolve independently. 
    - Jean's scale separates modes that grow, from modes that decay.
    - Show that the Jeans scale is the same as the sound horizon.
        - On length scales shorter than the Jean's scale, damped harmonic oscillations.
        - On length scales longer than the Jean's scale, growing modes, although no longer exponential due to the Hubble friction term. 

## Notes


## Reading

- The discussion of the fluid equations in the Newtonian limit is in Huterer 9.3 and Baumann 5.1
- Linear growth factors are discussed in Huterer 9.4 and Baumann 5.2. 
